### ISSUE TITLE
Backpacks get cleared when stored by FE inventory groups

### ISSUE THREAD

**Issue by olee** [Eydamos/Minecraft-Backpack-Mod#14]
Hi, I am one of the developers of (ForgeEssentials) and I would like to get your helpt to solve an issue I encountered when using a feature of FE that stores and swaps inventories together with backpacks.

The scenario is as follows:
On the server there can be certain areas where the player's inventory gets automatically swapped with another one as soon as he enters / leaves it. This works without a problem with other items that have NBT data assigned to them such as tool enchantments. It also works for backpacks in general.

However if the player leaves the server (or the server is stopped) and the backpack get stored to disk, it's inventory is empty after the player joins again and the backpack gets loaded again.

The NBT tags should definitely be loaded correctly (data is stored with GSON), as enchantments and other NBT stored data us restored without any errors. That is why I suspect the problem has something to do with the item being constructed first and then the NBT data gets loaded.

Could you try to point me to the correct places to check or do you have some idea why it could fail?

For reference:
- [Gson serializer for ItemStacks](https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/data/v2/types/ItemStackType.java#L68)
- [Gson serializer for NBT data](https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/data/v2/types/NBTTagCompoundType.java)

**Comment by Eydamos** [comment]
Hi,
I just saw your message. (Have to look into activating email notification)

The content of a backpack is stored in separate NBT files in the world folder.
Each ItemStack representing a backpack has a NBT value with a UUID.
This UUID is used as a file name for the NBT files that holds the content.

So please check if the UUID stored in the ItemStack is the same before and after the player has left the server or the server has stopped.
If it is the same check the content of the corresponding file. If the file is empty (or has no items data in it any more) for some reason we have to look deeper into how you set the NBT data on the ItemStack.

**Comment by olee** [comment]
I found the issue - was a fault on my side.
Sorry that I forgot to close this issue.
