### ISSUE TITLE
Crash Rendering Screen

### ISSUE THREAD

**Issue by NerdCraft** [Eydamos/Minecraft-Backpack-Mod#17]
When I open the Avaritia Table I get this crash:

1: https://pastebin.com/6QcpLg0g
2: https://pastebin.com/jdrZRkaP

**Comment by Eydamos** [comment]
This issue is cause by Avaritia Table. They are not checking if the recipe has an output but instead directly try to get the output of the recipe which fails as the items in the grid are missing.
As vanilla crafting tables don't crash it is not the fault of my mod.
