### ISSUE TITLE
Backpack model rendered on player even if player don't wear backpack

### ISSUE THREAD

**Issue by QuantumStatement** [Eydamos/Minecraft-Backpack-Mod#20]
Minecraft 1.12.2
Backpacks mod version 3.0.1
![2018-04-18_20 20 06](https://user-images.githubusercontent.com/35406698/38947815-8df5712e-4346-11e8-85e3-44538395bb5f.png)
![2018-04-18_20 20 16](https://user-images.githubusercontent.com/35406698/38947817-8e38fa34-4346-11e8-8166-6811287e017d.png)

**Comment by Eydamos** [comment]
Is this single player or are you connected to a server?

**Comment by QuantumStatement** [comment]
It's singleplayer

**Comment by Eydamos** [comment]
Issue will be fixed in next release. I plan to release it on Sunday
